# Generated by Django 3.0.3 on 2020-03-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('auteur', models.CharField(max_length=50)),
                ('resume', models.TextField(max_length=500)),
                ('couverture', models.ImageField(upload_to='couvertures/')),
                ('note', models.PositiveSmallIntegerField()),
                ('codeBarre', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=50)),
            ],
        ),
    ]
