# Generated by Django 3.0.3 on 2020-03-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livre',
            options={'ordering': ['titre']},
        ),
        migrations.AddField(
            model_name='livre',
            name='slug_title',
            field=models.SlugField(default=''),
        ),
    ]
