# Generated by Django 3.0.3 on 2020-03-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200301_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('imageProfil', models.ImageField(upload_to='imagesDeProfil/')),
                ('slug_pseudo', models.SlugField(default='')),
            ],
            options={
                'ordering': ['pseudo'],
            },
        ),
    ]
