# Generated by Django 3.0.3 on 2020-03-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='pseudo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='slug_pseudo',
            field=models.SlugField(default='', unique=True),
        ),
    ]
