# Generated by Django 3.0.3 on 2020-03-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200312_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='mail',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
