# Generated by Django 3.0.3 on 2020-03-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200312_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='mail',
            field=models.EmailField(default='fake@mail.comm', max_length=50),
        ),
    ]
