# Generated by Django 3.0.3 on 2020-03-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_membre_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='imageProfil',
            field=models.ImageField(blank=True, upload_to='imagesDeProfil/'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='mail',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
