# Generated by Django 3.0.3 on 2020-03-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200316_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='mail',
            field=models.EmailField(default='', error_messages={'required': 'Champ obligatoire'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='membre',
            name='pseudo',
            field=models.CharField(error_messages={'required': 'Champ obligatoire'}, max_length=50, unique=True),
        ),
    ]
