# Generated by Django 3.0.3 on 2020-03-21 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0015_auto_20200318_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membre',
            options={},
        ),
        migrations.RemoveField(
            model_name='membre',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='pseudo',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='slug_pseudo',
        ),
        migrations.AddField(
            model_name='membre',
            name='slug_username',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
