# Generated by Django 3.0.3 on 2020-03-22 09:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0016_auto_20200321_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membre',
            new_name='UserProfile',
        ),
    ]
