# Generated by Django 3.0.3 on 2020-03-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20200322_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='imageProfil',
            field=models.ImageField(blank=True, upload_to='imagesDeProfil/', verbose_name='Image de Profil'),
        ),
    ]
