# Generated by Django 3.0.3 on 2020-03-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20200322_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
