# Generated by Django 3.0.3 on 2020-04-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_bookbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug_username',
            field=models.SlugField(blank=True, default='rt', unique=True),
        ),
    ]
