# Generated by Django 3.0.3 on 2020-04-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20200401_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='imageProfil',
            field=models.ImageField(blank=True, default='static/images/profil_defaut.png', upload_to='imagesDeProfil/', verbose_name='Image de Profil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug_username',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
