# Generated by Django 3.0.3 on 2020-04-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20200401_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='resume',
            field=models.TextField(max_length=1000),
        ),
    ]
